### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by javere2x** [francojreyes/animixplay-sync#1]
hey my bad but I don't know where else to message you, but I downloaded the extension and it shows up next to the player, is it complete or how do I get it working?
![Screenshot 2022-08-14 212449](https://user-images.githubusercontent.com/93702143/184563123-33b2ed45-8c27-48ac-a1d6-b39ae0733036.png)

**Comment by francojreyes** [comment]
Hi javereg, assuming you've downloaded the latest release, once all users have clicked the `Sync` button you should be good to go, pressing play should start the video for all users.

This extension is far from in a complete state, however. If you are having issues, consider the 'Sync Watch' extension instead.
